---
apiVersion: v1
kind: Pod
metadata:
  name: covid
  labels:
    app: covid
spec:
  containers:
  - name: api-container
    image: n8snyder/370api:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
  - name: db-container
    image: n8snyder/370db:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: covid-service
  labels:
    app: covid
spec:
  type: NodePort
  selector:
    app: covid
  ports:
  - name: http
    protocol: TCP
    targetPort: 8080
    port: 80
    nodePort: 30001